### ISSUE TITLE
ArrayIndexOutOfBounds exception from ASM library during compile

### ISSUE THREAD

**Issue by jaccomoc** [jaccomoc/jactl#60]
Can get an ArrayIndexOutOfBoundsException from ASM library when compiling code like this:
```
   ''.map{ switch { /(c)/r -> [$1.size()] } }
```

Error is:
```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.objectweb.asm.Frame.merge(Frame.java:1280)
	at org.objectweb.asm.Frame.merge(Frame.java:1255)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1612)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1548)
	at io.jactl.compiler.MethodCompiler.compile(MethodCompiler.java:217)
	at io.jactl.compiler.ClassCompiler.doCompileMethod(ClassCompiler.java:410)
	at io.jactl.compiler.ClassCompiler.compileMethod(ClassCompiler.java:390)
	at io.jactl.compiler.MethodCompiler.visitClosure(MethodCompiler.java:1799)
	at io.jactl.compiler.MethodCompiler.visitClosure(MethodCompiler.java:170)
	at io.jactl.Expr$Closure.accept(Expr.java:601)
     ...
```

**Comment by jaccomoc** [comment]
Fixed with previous commit
